export const contents = [
	{
		pic: "/images/wine.jpg",
		tracking: "cc-123456789",
		status: "active",
		date: "30/11/2023",
		details: "view",
		update: "update",
		delete: "delete",
	},
	{
		image: "./assets/logo.jpg",
		tracking: "cc-123456789",
		status: "active",
		date: "30/11/2023",
		details: "view",
		update: "update",
		delete: "delete",
	},
	{
		image: "./assets/logo.jpg",
		tracking: "cc-123456789",
		status: "active",
		date: "30/11/2023",
		details: "view",
		update: "update",
		delete: "delete",
	},
	{
		image: "./assets/logo.jpg",
		tracking: "cc-123456789",
		status: "active",
		date: "30/11/2023",
		details: "view",
		update: "update",
		delete: "delete",
	},
	{
		image: "./assets/logo.jpg",
		tracking: "cc-123456789",
		status: "active",
		date: "30/11/2023",
		details: "view",
		update: "update",
		delete: "delete",
	},
];
